DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 3315 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 3316 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 3317 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 3318 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242 AND VALUE_SET_SEQUENCE = 1;
GO
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 1, 3315, 'EQ', 'N', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 1, 3316, 'CH', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 1, 3317, 'EQ', 'ENROUTE', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 1, 3318, 'NE', 'K_IDS_REQUEST,INCIDENT,PROBLEM', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:18:27', 126)));
GO

