DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 26 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 20 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 818 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 20 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 819 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 20 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 2295 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 20 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 3314 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 20 AND VALUE_SET_SEQUENCE = 1;
GO
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 20, 1, 26, 'CH', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUMANL', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-16T12:17:38', 126)), 'ADMIN', DATEADD(MILLISECOND,0, convert(datetime,'2019-08-02T01:32:56', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 20, 1, 818, 'EQ', 'INPROCESSWITH', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-25T00:07:51', 126)), NULL, NULL);
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 20, 1, 819, 'NE', 'K_IBS_REQUEST,INCIDENT', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUMANL', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-16T12:58:46', 126)), 'RUMANL', DATEADD(MILLISECOND,0, convert(datetime,'2019-08-02T01:32:56', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 20, 1, 2295, 'NE', 'C_TONER', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-25T00:09:14', 126)), NULL, NULL);
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 20, 1, 3314, 'EQ', 'Y', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
GO

