DELETE FROM PROCESS_RULE_INPUT_DEF WHERE INPUT_SEQUENCE = 3315 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242;
DELETE FROM PROCESS_RULE_INPUT_DEF WHERE INPUT_SEQUENCE = 3316 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242;
DELETE FROM PROCESS_RULE_INPUT_DEF WHERE INPUT_SEQUENCE = 3317 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242;
DELETE FROM PROCESS_RULE_INPUT_DEF WHERE INPUT_SEQUENCE = 3318 AND PROCESS_ID = 'C_INT_TASK_SVC_ORDER_CREATE' AND RULE_SEQUENCE = 1242;
GO
INSERT INTO PROCESS_RULE_INPUT_DEF (process_id, rule_sequence, input_sequence, table_name, column_name, use_original_value, use_expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 3315, 'TEAM', 'USER_DEF1', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:08:40', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:08:32', 126)));
INSERT INTO PROCESS_RULE_INPUT_DEF (process_id, rule_sequence, input_sequence, table_name, column_name, use_original_value, use_expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 3316, 'TASK', 'TASK_STATUS', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:08:48', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:08:40', 126)));
INSERT INTO PROCESS_RULE_INPUT_DEF (process_id, rule_sequence, input_sequence, table_name, column_name, use_original_value, use_expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 3317, 'TASK', 'TASK_STATUS', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:10:29', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:08:48', 126)));
INSERT INTO PROCESS_RULE_INPUT_DEF (process_id, rule_sequence, input_sequence, table_name, column_name, use_original_value, use_expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_INT_TASK_SVC_ORDER_CREATE', 1242, 3318, 'REQUEST', 'REQ_TYPE', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:10:39', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-03T09:10:29', 126)));
GO

