DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 2272 AND PROCESS_ID = 'C_PART_USAGE_LOCATION_FROM' AND RULE_SEQUENCE = 898 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 2274 AND PROCESS_ID = 'C_PART_USAGE_LOCATION_FROM' AND RULE_SEQUENCE = 898 AND VALUE_SET_SEQUENCE = 1;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 2272 AND PROCESS_ID = 'C_PART_USAGE_LOCATION_FROM' AND RULE_SEQUENCE = 898 AND VALUE_SET_SEQUENCE = 2;
DELETE FROM PROCESS_RULE_INPUT_VAL WHERE INPUT_SEQUENCE = 2274 AND PROCESS_ID = 'C_PART_USAGE_LOCATION_FROM' AND RULE_SEQUENCE = 898 AND VALUE_SET_SEQUENCE = 2;
GO
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PART_USAGE_LOCATION_FROM', 898, 1, 2272, 'EQ', 'C_TONER', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:43:51', 126)), 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:43:51', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PART_USAGE_LOCATION_FROM', 898, 1, 2274, 'EX', NULL, NULL, NULL, 'N', 'C_TASK_SAP_VIEW.IS_TPM="N" AND PART_USAGE.PLACE_ID_FROM IS NULL OR C_TASK_SAP_VIEW.IS_TPM="N" AND PART_USAGE.LOCATION IS NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER44', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-07T10:27:52', 126)), 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:43:51', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PART_USAGE_LOCATION_FROM', 898, 2, 2272, 'EQ', 'GENERIC,INCIDENT_SC,INSTALL', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:44:55', 126)), 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:44:55', 126)));
INSERT INTO PROCESS_RULE_INPUT_VAL (process_id, rule_sequence, value_set_sequence, input_sequence, operator, value, table_name, column_name, use_original_value, expression, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PART_USAGE_LOCATION_FROM', 898, 2, 2274, 'EX', NULL, NULL, NULL, 'N', 'C_TASK_SAP_VIEW.IS_TPM="N" AND PART_USAGE.PLACE_ID_FROM IS NULL OR C_TASK_SAP_VIEW.IS_TPM="N" AND PART_USAGE.LOCATION IS NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USER44', DATEADD(MILLISECOND,0, convert(datetime,'2020-07-07T10:28:42', 126)), 'USER293', DATEADD(MILLISECOND,0, convert(datetime,'2019-10-11T10:44:55', 126)));
GO

