DELETE FROM CUST_TABLE_DEF WHERE TABLE_NAME = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_COLUMN_DEF WHERE table_name = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_COLUMN_LKUP WHERE table_name = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_COLUMN_SELECT WHERE table_name = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_RELATION_DEF WHERE primary_tab_name = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_RELATION_MAP WHERE primary_tab_name = 'C_PRODUCT_SYNC_VIEW';
DELETE FROM CUST_DEFAULT_DEF WHERE primary_tab_name = 'C_PRODUCT_SYNC_VIEW';
GO
INSERT INTO CUST_TABLE_DEF (table_name, table_namespace, policy_name, policy_namespace, parent_policy, id_counter_name, id_column_name, id_cache_size, seq_column_name, parent_row_reqd, table_desc, label_value, desc_message_id, label_message_id, allow_import, allow_export, table_category, table_class, table_group, table_type, contains_tenant, master_tenant, archive_flag, archive_date_column, archive_older_than, alias_of_table_name, use_sequence, use_as_template, package_extract_group, package_extract_action, table_script, gdpr_personal, gdpr_cleanup, gdpr_purpose, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm, package_extractable) VALUES('C_PRODUCT_SYNC_VIEW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL, NULL, 'EXTRACT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)), 'N');
INSERT INTO CUST_COLUMN_DEF (table_name, column_name, in_database, is_key, is_required, is_readonly, force_select, column_type, default_value, max_chars, max_decimals, precision_adj, max_value, min_value, mask_type, template, column_desc, label_value, desc_message_id, label_message_id, is_unique, counter_name, url, regex_id, regex_value, regex_output_format, error_message_text, error_message_id, currency_column_name, gdpr_personal, gdpr_cleanup, gdpr_purpose, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PRODUCT_SYNC_VIEW', 'EFFECTIVE_DT', 'Y', 'N', 'N', 'Y', 'Y', 'DATETIME', NULL, NULL, NULL, NULL, NULL, NULL, 'NONE', NULL, NULL, 'Effective Dt', NULL, 'CProductSyncViewEffectiveDt', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)));
INSERT INTO CUST_COLUMN_DEF (table_name, column_name, in_database, is_key, is_required, is_readonly, force_select, column_type, default_value, max_chars, max_decimals, precision_adj, max_value, min_value, mask_type, template, column_desc, label_value, desc_message_id, label_message_id, is_unique, counter_name, url, regex_id, regex_value, regex_output_format, error_message_text, error_message_id, currency_column_name, gdpr_personal, gdpr_cleanup, gdpr_purpose, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PRODUCT_SYNC_VIEW', 'PERSON_ID', 'Y', 'Y', 'Y', 'Y', 'Y', 'STRING', NULL, 32, NULL, NULL, NULL, NULL, 'NONE', NULL, NULL, 'Person Id', NULL, 'CProductSyncViewPersonId', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)));
INSERT INTO CUST_COLUMN_DEF (table_name, column_name, in_database, is_key, is_required, is_readonly, force_select, column_type, default_value, max_chars, max_decimals, precision_adj, max_value, min_value, mask_type, template, column_desc, label_value, desc_message_id, label_message_id, is_unique, counter_name, url, regex_id, regex_value, regex_output_format, error_message_text, error_message_id, currency_column_name, gdpr_personal, gdpr_cleanup, gdpr_purpose, user_def1, user_def2, user_def3, user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, user_def11, user_def12, user_def13, user_def14, user_def15, user_def16, user_def17, user_def18, user_def19, user_def20, user_def21, user_def22, user_def23, user_def24, user_def25, user_def_dttm1, user_def_dttm2, user_def_dttm3, user_def_dttm4, user_def_dttm5, user_def_num1, user_def_num2, user_def_num3, user_def_num4, user_def_num5, modified_by, modified_dttm, created_by, created_dttm) VALUES('C_PRODUCT_SYNC_VIEW', 'PRODUCT_ID', 'Y', 'Y', 'Y', 'Y', 'Y', 'STRING', NULL, 32, NULL, NULL, NULL, NULL, 'NONE', NULL, NULL, 'Product Id', NULL, 'CProductSyncViewProductId', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)), '1000846', DATEADD(MILLISECOND,0, convert(datetime,'2020-06-22T12:35:43', 126)));
GO

